import java.util.List;
//import java.io.IOException;
import java.util.concurrent.ExecutionException;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import controllers.APIController;
import controllers.DbOperations;
import models.TimeSeriesCase;
import models.CountryTimeSeries;
//import okhttp3.OkHttpClient;
//import okhttp3.Request;
//import okhttp3.Response;







/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Owner
 */
public class CovidDataManagment extends javax.swing.JFrame {

   //private Object txtAreaMessage;
   
   APIController api = new APIController();
   DbOperations dbOperations = new DbOperations();
   

   /**
    * Creates new form CovidDataManagment
    */
   public CovidDataManagment() {
      initComponents();
      // set JFrame to appear centered, regardless of monitor resolution
      // Ορίσετε το JFrame να εμφανίζεται στο κέντρο,
      // ανεξάρτητα από την ανάλυση της οθόνης
      this.pack();
      this.setLocationRelativeTo(null);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      jButton5 = new javax.swing.JButton();
      jScorllPane1 = new javax.swing.JScrollPane();
      txtAreaMessage = new javax.swing.JTextArea();
      jLabel1 = new javax.swing.JLabel();

      setTitle("Σύστημα Covid19-Stats");
      setPreferredSize(new java.awt.Dimension(800, 600));
      setSize(new java.awt.Dimension(800, 600));
      getContentPane().setLayout(null);

      jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
      jButton1.setText("Εισαγωγή χωρών");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });
      getContentPane().add(jButton1);
      jButton1.setBounds(270, 120, 238, 43);

      jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
      jButton2.setText("Εισαγωγή δεδομένων");
      getContentPane().add(jButton2);
      jButton2.setBounds(270, 190, 238, 43);

      jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
      jButton3.setText("Διαγραφή δεδομένων");
      getContentPane().add(jButton3);
      jButton3.setBounds(270, 260, 238, 43);

      jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
      jButton4.setText("Διαγραφή χωρών  ");
      getContentPane().add(jButton4);
      jButton4.setBounds(270, 320, 238, 43);

      jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
      jButton5.setText("Έξοδος διαχείρισης δεδομένων");
      jButton5.setToolTipText("Έξοδος διαχείρισης δεδομένων");
      jButton5.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
         }
      });
      getContentPane().add(jButton5);
      jButton5.setBounds(540, 510, 238, 43);

      txtAreaMessage.setColumns(20);
      txtAreaMessage.setRows(5);
      jScorllPane1.setViewportView(txtAreaMessage);

      getContentPane().add(jScorllPane1);
      jScorllPane1.setBounds(150, 380, 490, 110);

      jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nick\\Desktop\\JavaCode\\3hGEnick\\src\\CovidPics\\covid19Background.png")); // NOI18N
      getContentPane().add(jLabel1);
      jLabel1.setBounds(-5, -2, 800, 600);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//      // TODO add your handling code here:

/////////////////////////////////////////////////////

        DisableAllButtons();
        txtAreaMessage.setText("ΠΑΡΑΚΑΛΩ ΠΕΡΙΜΕΝΕΤΕ.\n Εισαγωγή χωρών σε εξέλιξη.");
        SwingWorker sw1 = new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {
                List<CountryTimeSeries> ltm = api.GetTimeSeries(TimeSeriesCase.CONFIRMED);
                dbOperations.AddCountriesThatAreNotInDB(ltm);
                return null;
            }

            @Override
            protected void process(List chunks) {

            }

            @Override
            protected void done() {
                EnableAllButtons();
                txtAreaMessage.setText("");
            }
        };

        sw1.execute();





/////////////////////////////////////////////////////



   }//GEN-LAST:event_jButton1ActionPerformed

              

   public void EnableAllButtons() {
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        //jButton6.setEnabled(true);
        //jButton7.setEnabled(true);
    }

    public void DisableAllButtons() {
        jButton1.setEnabled(false);
        jButton1.setEnabled(false);
        jButton1.setEnabled(false);
        jButton1.setEnabled(false);
        jButton1.setEnabled(false);
        //jButton1.setEnabled(false);
        //jButton1.setEnabled(false);
    } 
   
   
   
   
   
   
   
   
   
   
   
   

   private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     
      super.setVisible(false);
           
   }//GEN-LAST:event_jButton5ActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JScrollPane jScorllPane1;
   private javax.swing.JTextArea txtAreaMessage;
   // End of variables declaration//GEN-END:variables

}