
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import okhttp3.OkHttpClient;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nick
 */
public class CovidViewDataMap extends javax.swing.JFrame {

   /**
    * Creates new form CovidViewDataMap
    */
   public CovidViewDataMap() {
      initComponents();
      // Ορίσετε το JFrame να εμφανίζεται στο κέντρο,
      // ανεξάρτητα από την ανάλυση της οθόνης
      this.pack();
      this.setLocationRelativeTo(null);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jComboBox1 = new javax.swing.JComboBox<>();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jLabel5 = new javax.swing.JLabel();

      setTitle("Σύστημα Covid19-Stats");
      setPreferredSize(new java.awt.Dimension(800, 600));
      getContentPane().setLayout(null);

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      jLabel1.setText("Επιλογή μιας βασικής χώρας");
      getContentPane().add(jLabel1);
      jLabel1.setBounds(100, 42, 173, 15);

      jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
      getContentPane().add(jComboBox1);
      jComboBox1.setBounds(100, 75, 173, 20);

      jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      jLabel2.setText("Πολλαπλή επιλογή λοιπόν χωρών");
      getContentPane().add(jLabel2);
      jLabel2.setBounds(404, 42, 206, 15);

      jLabel3.setText("Από Ημερομηνία");
      getContentPane().add(jLabel3);
      jLabel3.setBounds(100, 142, 78, 14);

      jLabel4.setText("Έως Ημερομηνία");
      getContentPane().add(jLabel4);
      jLabel4.setBounds(100, 185, 80, 14);

      jButton1.setText("Προβολή χάρτη");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });
      getContentPane().add(jButton1);
      jButton1.setBounds(404, 181, 151, 23);

      jButton2.setText("Έξοδος προβολής χάρτη");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });
      getContentPane().add(jButton2);
      jButton2.setBounds(404, 236, 151, 23);

      jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\nick\\Desktop\\JavaCode\\3hGEnick\\src\\CovidPics\\covid19Background.png")); // NOI18N
      getContentPane().add(jLabel5);
      jLabel5.setBounds(0, -1, 800, 600);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
       
      String urlToCall = "https://covid2019-api.herokuapp.com/timeseries/confirmed";
      OkHttpClient client = new OkHttpClient();

      String webpage="src\\covid19stats\\mappage.html";
      try {
         Runtime.getRuntime().exec("cmd /c start "+webpage);
      } catch (IOException ex) {            
         Logger.getLogger(CovidViewDataMap.class.getName()).log(Level.SEVERE, null, ex);            
      }
   }//GEN-LAST:event_jButton1ActionPerformed

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // TODO add your handling code here:
      //Closing JFrame with button click
      // Κλείσιμο του JFrame με κλικ στο κουμπί
      //this.dispose();
      //frameToClose.dispose();
      //super.dispose();
      //setVisible(false); //you can't see me!
      //dispose(); //Destroy the JFrame object
      super.setVisible(false);
   }//GEN-LAST:event_jButton2ActionPerformed

   /**
    * @param args the command line arguments
    */
     // Βάζω σε σχόλια την Public static void main Γιατί δεν χρειάζεται να καλείτε
//   public static void main(String args[]) {
//      /* Set the Nimbus look and feel */
//      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//       */
//      try {
//         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//            if ("Nimbus".equals(info.getName())) {
//               javax.swing.UIManager.setLookAndFeel(info.getClassName());
//               break;
//            }
//         }
//      } catch (ClassNotFoundException ex) {
//         java.util.logging.Logger.getLogger(CovidViewDataMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (InstantiationException ex) {
//         java.util.logging.Logger.getLogger(CovidViewDataMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (IllegalAccessException ex) {
//         java.util.logging.Logger.getLogger(CovidViewDataMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//         java.util.logging.Logger.getLogger(CovidViewDataMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      }
//      //</editor-fold>
//
//      /* Create and display the form */
//      java.awt.EventQueue.invokeLater(new Runnable() {
//         public void run() {
//            new CovidViewDataMap().setVisible(true);
//         }
//      });
//   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JComboBox<String> jComboBox1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   // End of variables declaration//GEN-END:variables
}
